version: '3'
services:
  react-app:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - '.:/usr/src/app'   
    expose:
      - 3000
    ports:
      - 3000:3000
    environment:
        - CHOKIDAR_USEPOLLING=true  